name: HA Config Sync
version: "1.6.1"
slug: ha_config_sync
description: Copies selected Home Assistant configuration to Git and pushes it. To edit Git ignore rules, select Open Web UI.
url: https://github.com/<YOUR USER NAME>/ha-config
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: mdi:file-document-edit-outline
panel_title: Git Ignore Editor
panel_admin: false
map:
  - config:rw
options:
  repository_url: https://github.com/<YOUR USER NAME>/homeassistant-config-files.git
  branch: main
  git_name: Home Assistant Config Sync
  git_email: home-assistant@local
  github_token: ""
  include_secrets: false
  include_dashboards: true
  sync_interval_hours: 4
schema:
  repository_url: str
  branch: str
  git_name: str
  git_email: email
  github_token: password
  include_secrets: bool
  include_dashboards: bool
  sync_interval_hours: int(1,168)
